### ISSUE TITLE
Updating the readme code examples

### ISSUE THREAD

**Issue by kentico-anthonym** [Kentico/kontent-management-sdk-js#11]
### Brief bug description
The readme examples seem to be out of date, also to expand on the currently available code samples.

**Comment by Enngage** [comment]
What is outdated in the readme? I'm not aware of anything outdated in the readme.

**Comment by kentico-ericd** [comment]
From the conversation with the customer:

> client.addAsset()
.withData(
{
// To create a file reference, see the "Upload a binary file" endpoint
fileReference: {
id: 'fcbb12e6-66a3-4672-85d9-d502d16b8d9c',
type: 'internal'
},
title: 'Coffee Brewing Techniques',
externalId: 'which-brewing-fits-you',

> fileReference should be file_reference

> and externalId should be external_id

However, it looks like they're referring to Kontent documentation rather than the repo: https://docs.kontent.ai/reference/management-api-v2#operation/add-an-asset. I've tagged the conversation so this can probably be closed.

**Comment by Enngage** [comment]
Thanks @kentico-ericd ! Closing this issue then.
